name: token_local_storage
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  build_runner: ^2.4.15
  hive_ce_generator: ^1.8.2
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
  
dependencies:
  fresh_dio: ^0.4.3
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  meta: ^1.15.0
  synchronized: ^3.3.0+3
