name: user_app_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.5.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  user_repository:
    path: packages/user_repository
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  user_app_api:
    path: packages/user_app_api
  stream_listener: 
    path: packages/stream_listener
  json_annotation: ^4.9.0
  go_router: ^14.8.1
  hydrated_bloc: ^9.1.5
  formz: ^0.8.0
  freezed_annotation: ^3.0.0
  bloc: ^8.1.4
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  bloc_concurrency: ^0.2.5
  stream_transform: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.9.4
  mocktail: ^1.0.3
  go_router_builder: ^2.8.2
  very_good_analysis: ^7.0.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: assets/icon/splash.png
  image_dark: assets/icon/splash.png
  android: true
  ios: true
  android_12:
    image: assets/icon/splash.png
    image_dark: assets/icon/splash.png
    color: "#FFFFFF"
    color_dark: "#121212"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#121212"
  