name: user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

dependencies:
  freezed_annotation: ^3.0.0
  user_app_api:
    path: ../user_app_api
